"""services.quote_xlsx — G2b: 报价单 XLSX 附件闭环.

镜像 services/quote_pdf 铁律 (客户要 XLSX/PDF "都可以行"):
  - content_sha256 锁"报价事实" — 复用 quote_pdf._content_payload 保证与 PDF 同源同锁;
  - draft_only: 附件只进草稿, 永不自动外发;
  - openpyxl 为可选依赖: 缺库 → 显式降级 (attachment_error=openpyxl_not_installed), 不炸链。
"""
from __future__ import annotations

import hashlib
import logging
from pathlib import Path
from typing import Any, Dict, Optional

log = logging.getLogger(__name__)

_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ARTIFACTS_DIR = _ROOT / "data" / "artifacts"


def _openpyxl_available() -> bool:
    try:
        import openpyxl  # noqa: F401
        return True
    except Exception:
        return False


def render_quote_xlsx(
    quote: Dict[str, Any],
    context_id: str,
    out_dir: Optional[Path] = None,
    customer: Optional[Dict[str, Any]] = None,
    rfq: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """渲染报价 XLSX → out_dir/{context_id}/quote-{context_id}-{sha8}.xlsx.

    返回:
      ok=True  → {"ok", "path", "content_sha256", "context_id"}
      ok=False → {"ok": False, "reason": "no_price" | "openpyxl_not_installed", "context_id"}
    """
    from services.quote_pdf import _canon, _content_payload, _has_price

    out_dir = Path(out_dir) if out_dir else DEFAULT_ARTIFACTS_DIR
    quote = quote or {}
    customer = customer or {}
    rfq = rfq or {}

    if not _has_price(quote):
        return {"ok": False, "reason": "no_price", "context_id": context_id}
    if not _openpyxl_available():
        return {"ok": False, "reason": "openpyxl_not_installed", "context_id": context_id}

    payload = _content_payload(context_id, quote, customer, rfq)
    content_sha = hashlib.sha256(_canon(payload).encode("utf-8")).hexdigest()

    target_dir = out_dir / context_id
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"quote-{context_id}-{content_sha[:8]}.xlsx"

    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill
        from openpyxl.utils import get_column_letter

        wb = Workbook()
        ws = wb.active
        ws.title = "Quotation"
        head_fill = PatternFill("solid", fgColor="F1F5F9")
        warn_font = Font(color="B91C1C", size=9)
        head_font = Font(bold=True)

        cur = payload["currency"] or "CNY"
        rows = [
            [f"Quotation {context_id} — DRAFT ONLY", "", "", ""],
            ["Customer", payload["customer"] or "N/A", "Material", payload["material"] or "N/A"],
            ["Quantity", payload["quantity"] or "-", "Surface", payload["surface"] or "as-machined"],
            ["Tolerance", payload["tolerance_grade"] or "standard",
             "Lead time (days)", payload["lead_time_days"] or "TBD"],
            [],
            ["Description", "Qty", f"Unit ({cur})", f"Total ({cur})"],
            [f"{payload['material'] or 'Part'} ({payload['surface'] or 'as-machined'}, "
             f"{payload['tolerance_grade'] or 'standard'})",
             payload["quantity"] or "-",
             payload["unit_price"] if payload["unit_price"] is not None else "-",
             payload["final_price"] if payload["final_price"] is not None else "-"],
            [],
            ["Engine", payload["engine_source"], "Content lock", f"sha256:{content_sha[:16]}…"],
            ["DRAFT ONLY — generated by the deterministic manufacturing engine; "
             "valid 14 days, subject to final drawing confirmation. "
             "This attachment is never auto-sent (iron rule 1).", "", "", ""],
        ]
        for r in rows:
            ws.append(r)
        # 表头行 (第6行) 加粗+底色; 数据行右对齐
        for cell in ws[6]:
            cell.font = head_font
            cell.fill = head_fill
        for cell in ws[7][1:]:
            cell.alignment = Alignment(horizontal="right")
        for cell in ws[10]:
            cell.font = warn_font
        widths = [46, 10, 14, 14]
        for i, w in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(i)].width = w

        wb.save(path)
    except Exception as e:
        log.exception("[quote-xlsx] render failed for %s: %r", context_id, e)
        return {"ok": False, "reason": f"render_failed: {e!r}", "context_id": context_id}

    return {
        "ok": True,
        "path": str(path),
        "content_sha256": content_sha,
        "context_id": context_id,
    }


def attach_quote_xlsx(
    draft: Dict[str, Any],
    quote: Dict[str, Any],
    context_id: str,
    customer: Optional[Dict[str, Any]] = None,
    rfq: Optional[Dict[str, Any]] = None,
    out_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """把报价 XLSX 作为附件挂到回复草稿 (draft_only 不变)."""
    r = render_quote_xlsx(quote, context_id, out_dir=out_dir, customer=customer, rfq=rfq)
    if r.get("ok"):
        draft["attachments"] = draft.get("attachments") or []
        draft["attachments"].append({
            "kind": "quote_xlsx",
            "path": r["path"],
            "content_sha256": r["content_sha256"],
            "draft_only": True,
        })
        draft["attachment_error"] = None
    else:
        draft["attachments"] = draft.get("attachments") or []
        if r.get("reason") != "no_price":
            draft["attachment_error"] = r.get("reason")
    return draft
